//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ec1GroupProject.AirlineService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flight", Namespace="http://Airlinebook.com/")]
    [System.SerializableAttribute()]
    public partial class Flight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string airline_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string flight_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departdateField;
        
        private float PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string arrivalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string airline_id {
            get {
                return this.airline_idField;
            }
            set {
                if ((object.ReferenceEquals(this.airline_idField, value) != true)) {
                    this.airline_idField = value;
                    this.RaisePropertyChanged("airline_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string flight_id {
            get {
                return this.flight_idField;
            }
            set {
                if ((object.ReferenceEquals(this.flight_idField, value) != true)) {
                    this.flight_idField = value;
                    this.RaisePropertyChanged("flight_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string departdate {
            get {
                return this.departdateField;
            }
            set {
                if ((object.ReferenceEquals(this.departdateField, value) != true)) {
                    this.departdateField = value;
                    this.RaisePropertyChanged("departdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Departure {
            get {
                return this.DepartureField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureField, value) != true)) {
                    this.DepartureField = value;
                    this.RaisePropertyChanged("Departure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arrival {
            get {
                return this.arrivalField;
            }
            set {
                if ((object.ReferenceEquals(this.arrivalField, value) != true)) {
                    this.arrivalField = value;
                    this.RaisePropertyChanged("arrival");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Airlinebook.com/", ConfigurationName="AirlineService.AirlineSystemSoap")]
    public interface AirlineSystemSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://Airlinebook.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Airlinebook.com/HelloWorld", ReplyAction="*")]
        Ec1GroupProject.AirlineService.HelloWorldResponse HelloWorld(Ec1GroupProject.AirlineService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Airlinebook.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.HelloWorldResponse> HelloWorldAsync(Ec1GroupProject.AirlineService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name dep from namespace http://Airlinebook.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Airlinebook.com/DisplayFlights", ReplyAction="*")]
        Ec1GroupProject.AirlineService.DisplayFlightsResponse DisplayFlights(Ec1GroupProject.AirlineService.DisplayFlightsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Airlinebook.com/DisplayFlights", ReplyAction="*")]
        System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.DisplayFlightsResponse> DisplayFlightsAsync(Ec1GroupProject.AirlineService.DisplayFlightsRequest request);
        
        // CODEGEN: Generating message contract since element name dep from namespace http://Airlinebook.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Airlinebook.com/Display", ReplyAction="*")]
        Ec1GroupProject.AirlineService.DisplayResponse Display(Ec1GroupProject.AirlineService.DisplayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Airlinebook.com/Display", ReplyAction="*")]
        System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.DisplayResponse> DisplayAsync(Ec1GroupProject.AirlineService.DisplayRequest request);
        
        // CODEGEN: Generating message contract since element name yooResult from namespace http://Airlinebook.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Airlinebook.com/yoo", ReplyAction="*")]
        Ec1GroupProject.AirlineService.yooResponse yoo(Ec1GroupProject.AirlineService.yooRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Airlinebook.com/yoo", ReplyAction="*")]
        System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.yooResponse> yooAsync(Ec1GroupProject.AirlineService.yooRequest request);
        
        // CODEGEN: Generating message contract since element name flyid from namespace http://Airlinebook.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Airlinebook.com/BookFlight", ReplyAction="*")]
        Ec1GroupProject.AirlineService.BookFlightResponse BookFlight(Ec1GroupProject.AirlineService.BookFlightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Airlinebook.com/BookFlight", ReplyAction="*")]
        System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.BookFlightResponse> BookFlightAsync(Ec1GroupProject.AirlineService.BookFlightRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://Airlinebook.com/", Order=0)]
        public Ec1GroupProject.AirlineService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Ec1GroupProject.AirlineService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://Airlinebook.com/", Order=0)]
        public Ec1GroupProject.AirlineService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Ec1GroupProject.AirlineService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Airlinebook.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DisplayFlightsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DisplayFlights", Namespace="http://Airlinebook.com/", Order=0)]
        public Ec1GroupProject.AirlineService.DisplayFlightsRequestBody Body;
        
        public DisplayFlightsRequest() {
        }
        
        public DisplayFlightsRequest(Ec1GroupProject.AirlineService.DisplayFlightsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Airlinebook.com/")]
    public partial class DisplayFlightsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dep;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arr;
        
        public DisplayFlightsRequestBody() {
        }
        
        public DisplayFlightsRequestBody(string dep, string date, string arr) {
            this.dep = dep;
            this.date = date;
            this.arr = arr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DisplayFlightsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DisplayFlightsResponse", Namespace="http://Airlinebook.com/", Order=0)]
        public Ec1GroupProject.AirlineService.DisplayFlightsResponseBody Body;
        
        public DisplayFlightsResponse() {
        }
        
        public DisplayFlightsResponse(Ec1GroupProject.AirlineService.DisplayFlightsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Airlinebook.com/")]
    public partial class DisplayFlightsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ec1GroupProject.AirlineService.Flight[] DisplayFlightsResult;
        
        public DisplayFlightsResponseBody() {
        }
        
        public DisplayFlightsResponseBody(Ec1GroupProject.AirlineService.Flight[] DisplayFlightsResult) {
            this.DisplayFlightsResult = DisplayFlightsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DisplayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Display", Namespace="http://Airlinebook.com/", Order=0)]
        public Ec1GroupProject.AirlineService.DisplayRequestBody Body;
        
        public DisplayRequest() {
        }
        
        public DisplayRequest(Ec1GroupProject.AirlineService.DisplayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Airlinebook.com/")]
    public partial class DisplayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dep;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arr;
        
        public DisplayRequestBody() {
        }
        
        public DisplayRequestBody(string dep, string date, string arr) {
            this.dep = dep;
            this.date = date;
            this.arr = arr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DisplayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DisplayResponse", Namespace="http://Airlinebook.com/", Order=0)]
        public Ec1GroupProject.AirlineService.DisplayResponseBody Body;
        
        public DisplayResponse() {
        }
        
        public DisplayResponse(Ec1GroupProject.AirlineService.DisplayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Airlinebook.com/")]
    public partial class DisplayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ec1GroupProject.AirlineService.Flight[] DisplayResult;
        
        public DisplayResponseBody() {
        }
        
        public DisplayResponseBody(Ec1GroupProject.AirlineService.Flight[] DisplayResult) {
            this.DisplayResult = DisplayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class yooRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="yoo", Namespace="http://Airlinebook.com/", Order=0)]
        public Ec1GroupProject.AirlineService.yooRequestBody Body;
        
        public yooRequest() {
        }
        
        public yooRequest(Ec1GroupProject.AirlineService.yooRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class yooRequestBody {
        
        public yooRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class yooResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="yooResponse", Namespace="http://Airlinebook.com/", Order=0)]
        public Ec1GroupProject.AirlineService.yooResponseBody Body;
        
        public yooResponse() {
        }
        
        public yooResponse(Ec1GroupProject.AirlineService.yooResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Airlinebook.com/")]
    public partial class yooResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string yooResult;
        
        public yooResponseBody() {
        }
        
        public yooResponseBody(string yooResult) {
            this.yooResult = yooResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookFlightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookFlight", Namespace="http://Airlinebook.com/", Order=0)]
        public Ec1GroupProject.AirlineService.BookFlightRequestBody Body;
        
        public BookFlightRequest() {
        }
        
        public BookFlightRequest(Ec1GroupProject.AirlineService.BookFlightRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Airlinebook.com/")]
    public partial class BookFlightRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string flyid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string db;
        
        public BookFlightRequestBody() {
        }
        
        public BookFlightRequestBody(string flyid, string nm, string db) {
            this.flyid = flyid;
            this.nm = nm;
            this.db = db;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookFlightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookFlightResponse", Namespace="http://Airlinebook.com/", Order=0)]
        public Ec1GroupProject.AirlineService.BookFlightResponseBody Body;
        
        public BookFlightResponse() {
        }
        
        public BookFlightResponse(Ec1GroupProject.AirlineService.BookFlightResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Airlinebook.com/")]
    public partial class BookFlightResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BookFlightResult;
        
        public BookFlightResponseBody() {
        }
        
        public BookFlightResponseBody(string BookFlightResult) {
            this.BookFlightResult = BookFlightResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AirlineSystemSoapChannel : Ec1GroupProject.AirlineService.AirlineSystemSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AirlineSystemSoapClient : System.ServiceModel.ClientBase<Ec1GroupProject.AirlineService.AirlineSystemSoap>, Ec1GroupProject.AirlineService.AirlineSystemSoap {
        
        public AirlineSystemSoapClient() {
        }
        
        public AirlineSystemSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AirlineSystemSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirlineSystemSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirlineSystemSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ec1GroupProject.AirlineService.HelloWorldResponse Ec1GroupProject.AirlineService.AirlineSystemSoap.HelloWorld(Ec1GroupProject.AirlineService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Ec1GroupProject.AirlineService.HelloWorldRequest inValue = new Ec1GroupProject.AirlineService.HelloWorldRequest();
            inValue.Body = new Ec1GroupProject.AirlineService.HelloWorldRequestBody();
            Ec1GroupProject.AirlineService.HelloWorldResponse retVal = ((Ec1GroupProject.AirlineService.AirlineSystemSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.HelloWorldResponse> Ec1GroupProject.AirlineService.AirlineSystemSoap.HelloWorldAsync(Ec1GroupProject.AirlineService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.HelloWorldResponse> HelloWorldAsync() {
            Ec1GroupProject.AirlineService.HelloWorldRequest inValue = new Ec1GroupProject.AirlineService.HelloWorldRequest();
            inValue.Body = new Ec1GroupProject.AirlineService.HelloWorldRequestBody();
            return ((Ec1GroupProject.AirlineService.AirlineSystemSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ec1GroupProject.AirlineService.DisplayFlightsResponse Ec1GroupProject.AirlineService.AirlineSystemSoap.DisplayFlights(Ec1GroupProject.AirlineService.DisplayFlightsRequest request) {
            return base.Channel.DisplayFlights(request);
        }
        
        public Ec1GroupProject.AirlineService.Flight[] DisplayFlights(string dep, string date, string arr) {
            Ec1GroupProject.AirlineService.DisplayFlightsRequest inValue = new Ec1GroupProject.AirlineService.DisplayFlightsRequest();
            inValue.Body = new Ec1GroupProject.AirlineService.DisplayFlightsRequestBody();
            inValue.Body.dep = dep;
            inValue.Body.date = date;
            inValue.Body.arr = arr;
            Ec1GroupProject.AirlineService.DisplayFlightsResponse retVal = ((Ec1GroupProject.AirlineService.AirlineSystemSoap)(this)).DisplayFlights(inValue);
            return retVal.Body.DisplayFlightsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.DisplayFlightsResponse> Ec1GroupProject.AirlineService.AirlineSystemSoap.DisplayFlightsAsync(Ec1GroupProject.AirlineService.DisplayFlightsRequest request) {
            return base.Channel.DisplayFlightsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.DisplayFlightsResponse> DisplayFlightsAsync(string dep, string date, string arr) {
            Ec1GroupProject.AirlineService.DisplayFlightsRequest inValue = new Ec1GroupProject.AirlineService.DisplayFlightsRequest();
            inValue.Body = new Ec1GroupProject.AirlineService.DisplayFlightsRequestBody();
            inValue.Body.dep = dep;
            inValue.Body.date = date;
            inValue.Body.arr = arr;
            return ((Ec1GroupProject.AirlineService.AirlineSystemSoap)(this)).DisplayFlightsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ec1GroupProject.AirlineService.DisplayResponse Ec1GroupProject.AirlineService.AirlineSystemSoap.Display(Ec1GroupProject.AirlineService.DisplayRequest request) {
            return base.Channel.Display(request);
        }
        
        public Ec1GroupProject.AirlineService.Flight[] Display(string dep, string date, string arr) {
            Ec1GroupProject.AirlineService.DisplayRequest inValue = new Ec1GroupProject.AirlineService.DisplayRequest();
            inValue.Body = new Ec1GroupProject.AirlineService.DisplayRequestBody();
            inValue.Body.dep = dep;
            inValue.Body.date = date;
            inValue.Body.arr = arr;
            Ec1GroupProject.AirlineService.DisplayResponse retVal = ((Ec1GroupProject.AirlineService.AirlineSystemSoap)(this)).Display(inValue);
            return retVal.Body.DisplayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.DisplayResponse> Ec1GroupProject.AirlineService.AirlineSystemSoap.DisplayAsync(Ec1GroupProject.AirlineService.DisplayRequest request) {
            return base.Channel.DisplayAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.DisplayResponse> DisplayAsync(string dep, string date, string arr) {
            Ec1GroupProject.AirlineService.DisplayRequest inValue = new Ec1GroupProject.AirlineService.DisplayRequest();
            inValue.Body = new Ec1GroupProject.AirlineService.DisplayRequestBody();
            inValue.Body.dep = dep;
            inValue.Body.date = date;
            inValue.Body.arr = arr;
            return ((Ec1GroupProject.AirlineService.AirlineSystemSoap)(this)).DisplayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ec1GroupProject.AirlineService.yooResponse Ec1GroupProject.AirlineService.AirlineSystemSoap.yoo(Ec1GroupProject.AirlineService.yooRequest request) {
            return base.Channel.yoo(request);
        }
        
        public string yoo() {
            Ec1GroupProject.AirlineService.yooRequest inValue = new Ec1GroupProject.AirlineService.yooRequest();
            inValue.Body = new Ec1GroupProject.AirlineService.yooRequestBody();
            Ec1GroupProject.AirlineService.yooResponse retVal = ((Ec1GroupProject.AirlineService.AirlineSystemSoap)(this)).yoo(inValue);
            return retVal.Body.yooResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.yooResponse> Ec1GroupProject.AirlineService.AirlineSystemSoap.yooAsync(Ec1GroupProject.AirlineService.yooRequest request) {
            return base.Channel.yooAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.yooResponse> yooAsync() {
            Ec1GroupProject.AirlineService.yooRequest inValue = new Ec1GroupProject.AirlineService.yooRequest();
            inValue.Body = new Ec1GroupProject.AirlineService.yooRequestBody();
            return ((Ec1GroupProject.AirlineService.AirlineSystemSoap)(this)).yooAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ec1GroupProject.AirlineService.BookFlightResponse Ec1GroupProject.AirlineService.AirlineSystemSoap.BookFlight(Ec1GroupProject.AirlineService.BookFlightRequest request) {
            return base.Channel.BookFlight(request);
        }
        
        public string BookFlight(string flyid, string nm, string db) {
            Ec1GroupProject.AirlineService.BookFlightRequest inValue = new Ec1GroupProject.AirlineService.BookFlightRequest();
            inValue.Body = new Ec1GroupProject.AirlineService.BookFlightRequestBody();
            inValue.Body.flyid = flyid;
            inValue.Body.nm = nm;
            inValue.Body.db = db;
            Ec1GroupProject.AirlineService.BookFlightResponse retVal = ((Ec1GroupProject.AirlineService.AirlineSystemSoap)(this)).BookFlight(inValue);
            return retVal.Body.BookFlightResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.BookFlightResponse> Ec1GroupProject.AirlineService.AirlineSystemSoap.BookFlightAsync(Ec1GroupProject.AirlineService.BookFlightRequest request) {
            return base.Channel.BookFlightAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ec1GroupProject.AirlineService.BookFlightResponse> BookFlightAsync(string flyid, string nm, string db) {
            Ec1GroupProject.AirlineService.BookFlightRequest inValue = new Ec1GroupProject.AirlineService.BookFlightRequest();
            inValue.Body = new Ec1GroupProject.AirlineService.BookFlightRequestBody();
            inValue.Body.flyid = flyid;
            inValue.Body.nm = nm;
            inValue.Body.db = db;
            return ((Ec1GroupProject.AirlineService.AirlineSystemSoap)(this)).BookFlightAsync(inValue);
        }
    }
}
