//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ec1GroupProject.CruiseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://HotelSystem.com/", ConfigurationName="CruiseService.CruiseSystemSoap")]
    public interface CruiseSystemSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://HotelSystem.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://HotelSystem.com/HelloWorld", ReplyAction="*")]
        Ec1GroupProject.CruiseService.HelloWorldResponse HelloWorld(Ec1GroupProject.CruiseService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HotelSystem.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Ec1GroupProject.CruiseService.HelloWorldResponse> HelloWorldAsync(Ec1GroupProject.CruiseService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name chin from namespace http://HotelSystem.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://HotelSystem.com/DisplayAvailable", ReplyAction="*")]
        Ec1GroupProject.CruiseService.DisplayAvailableResponse DisplayAvailable(Ec1GroupProject.CruiseService.DisplayAvailableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HotelSystem.com/DisplayAvailable", ReplyAction="*")]
        System.Threading.Tasks.Task<Ec1GroupProject.CruiseService.DisplayAvailableResponse> DisplayAvailableAsync(Ec1GroupProject.CruiseService.DisplayAvailableRequest request);
        
        // CODEGEN: Generating message contract since element name chin from namespace http://HotelSystem.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://HotelSystem.com/BookRoom", ReplyAction="*")]
        Ec1GroupProject.CruiseService.BookRoomResponse BookRoom(Ec1GroupProject.CruiseService.BookRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HotelSystem.com/BookRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<Ec1GroupProject.CruiseService.BookRoomResponse> BookRoomAsync(Ec1GroupProject.CruiseService.BookRoomRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://HotelSystem.com/", Order=0)]
        public Ec1GroupProject.CruiseService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Ec1GroupProject.CruiseService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://HotelSystem.com/", Order=0)]
        public Ec1GroupProject.CruiseService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Ec1GroupProject.CruiseService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://HotelSystem.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DisplayAvailableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DisplayAvailable", Namespace="http://HotelSystem.com/", Order=0)]
        public Ec1GroupProject.CruiseService.DisplayAvailableRequestBody Body;
        
        public DisplayAvailableRequest() {
        }
        
        public DisplayAvailableRequest(Ec1GroupProject.CruiseService.DisplayAvailableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://HotelSystem.com/")]
    public partial class DisplayAvailableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string chin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string chout;
        
        public DisplayAvailableRequestBody() {
        }
        
        public DisplayAvailableRequestBody(string chin, string chout) {
            this.chin = chin;
            this.chout = chout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DisplayAvailableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DisplayAvailableResponse", Namespace="http://HotelSystem.com/", Order=0)]
        public Ec1GroupProject.CruiseService.DisplayAvailableResponseBody Body;
        
        public DisplayAvailableResponse() {
        }
        
        public DisplayAvailableResponse(Ec1GroupProject.CruiseService.DisplayAvailableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://HotelSystem.com/")]
    public partial class DisplayAvailableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DisplayAvailableResult;
        
        public DisplayAvailableResponseBody() {
        }
        
        public DisplayAvailableResponseBody(string DisplayAvailableResult) {
            this.DisplayAvailableResult = DisplayAvailableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookRoom", Namespace="http://HotelSystem.com/", Order=0)]
        public Ec1GroupProject.CruiseService.BookRoomRequestBody Body;
        
        public BookRoomRequest() {
        }
        
        public BookRoomRequest(Ec1GroupProject.CruiseService.BookRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://HotelSystem.com/")]
    public partial class BookRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int rnum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string chin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string chout;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nm;
        
        public BookRoomRequestBody() {
        }
        
        public BookRoomRequestBody(int rnum, string chin, string chout, string type, string nm) {
            this.rnum = rnum;
            this.chin = chin;
            this.chout = chout;
            this.type = type;
            this.nm = nm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookRoomResponse", Namespace="http://HotelSystem.com/", Order=0)]
        public Ec1GroupProject.CruiseService.BookRoomResponseBody Body;
        
        public BookRoomResponse() {
        }
        
        public BookRoomResponse(Ec1GroupProject.CruiseService.BookRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://HotelSystem.com/")]
    public partial class BookRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BookRoomResult;
        
        public BookRoomResponseBody() {
        }
        
        public BookRoomResponseBody(string BookRoomResult) {
            this.BookRoomResult = BookRoomResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CruiseSystemSoapChannel : Ec1GroupProject.CruiseService.CruiseSystemSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CruiseSystemSoapClient : System.ServiceModel.ClientBase<Ec1GroupProject.CruiseService.CruiseSystemSoap>, Ec1GroupProject.CruiseService.CruiseSystemSoap {
        
        public CruiseSystemSoapClient() {
        }
        
        public CruiseSystemSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CruiseSystemSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CruiseSystemSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CruiseSystemSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ec1GroupProject.CruiseService.HelloWorldResponse Ec1GroupProject.CruiseService.CruiseSystemSoap.HelloWorld(Ec1GroupProject.CruiseService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Ec1GroupProject.CruiseService.HelloWorldRequest inValue = new Ec1GroupProject.CruiseService.HelloWorldRequest();
            inValue.Body = new Ec1GroupProject.CruiseService.HelloWorldRequestBody();
            Ec1GroupProject.CruiseService.HelloWorldResponse retVal = ((Ec1GroupProject.CruiseService.CruiseSystemSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ec1GroupProject.CruiseService.HelloWorldResponse> Ec1GroupProject.CruiseService.CruiseSystemSoap.HelloWorldAsync(Ec1GroupProject.CruiseService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ec1GroupProject.CruiseService.HelloWorldResponse> HelloWorldAsync() {
            Ec1GroupProject.CruiseService.HelloWorldRequest inValue = new Ec1GroupProject.CruiseService.HelloWorldRequest();
            inValue.Body = new Ec1GroupProject.CruiseService.HelloWorldRequestBody();
            return ((Ec1GroupProject.CruiseService.CruiseSystemSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ec1GroupProject.CruiseService.DisplayAvailableResponse Ec1GroupProject.CruiseService.CruiseSystemSoap.DisplayAvailable(Ec1GroupProject.CruiseService.DisplayAvailableRequest request) {
            return base.Channel.DisplayAvailable(request);
        }
        
        public string DisplayAvailable(string chin, string chout) {
            Ec1GroupProject.CruiseService.DisplayAvailableRequest inValue = new Ec1GroupProject.CruiseService.DisplayAvailableRequest();
            inValue.Body = new Ec1GroupProject.CruiseService.DisplayAvailableRequestBody();
            inValue.Body.chin = chin;
            inValue.Body.chout = chout;
            Ec1GroupProject.CruiseService.DisplayAvailableResponse retVal = ((Ec1GroupProject.CruiseService.CruiseSystemSoap)(this)).DisplayAvailable(inValue);
            return retVal.Body.DisplayAvailableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ec1GroupProject.CruiseService.DisplayAvailableResponse> Ec1GroupProject.CruiseService.CruiseSystemSoap.DisplayAvailableAsync(Ec1GroupProject.CruiseService.DisplayAvailableRequest request) {
            return base.Channel.DisplayAvailableAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ec1GroupProject.CruiseService.DisplayAvailableResponse> DisplayAvailableAsync(string chin, string chout) {
            Ec1GroupProject.CruiseService.DisplayAvailableRequest inValue = new Ec1GroupProject.CruiseService.DisplayAvailableRequest();
            inValue.Body = new Ec1GroupProject.CruiseService.DisplayAvailableRequestBody();
            inValue.Body.chin = chin;
            inValue.Body.chout = chout;
            return ((Ec1GroupProject.CruiseService.CruiseSystemSoap)(this)).DisplayAvailableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ec1GroupProject.CruiseService.BookRoomResponse Ec1GroupProject.CruiseService.CruiseSystemSoap.BookRoom(Ec1GroupProject.CruiseService.BookRoomRequest request) {
            return base.Channel.BookRoom(request);
        }
        
        public string BookRoom(int rnum, string chin, string chout, string type, string nm) {
            Ec1GroupProject.CruiseService.BookRoomRequest inValue = new Ec1GroupProject.CruiseService.BookRoomRequest();
            inValue.Body = new Ec1GroupProject.CruiseService.BookRoomRequestBody();
            inValue.Body.rnum = rnum;
            inValue.Body.chin = chin;
            inValue.Body.chout = chout;
            inValue.Body.type = type;
            inValue.Body.nm = nm;
            Ec1GroupProject.CruiseService.BookRoomResponse retVal = ((Ec1GroupProject.CruiseService.CruiseSystemSoap)(this)).BookRoom(inValue);
            return retVal.Body.BookRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ec1GroupProject.CruiseService.BookRoomResponse> Ec1GroupProject.CruiseService.CruiseSystemSoap.BookRoomAsync(Ec1GroupProject.CruiseService.BookRoomRequest request) {
            return base.Channel.BookRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ec1GroupProject.CruiseService.BookRoomResponse> BookRoomAsync(int rnum, string chin, string chout, string type, string nm) {
            Ec1GroupProject.CruiseService.BookRoomRequest inValue = new Ec1GroupProject.CruiseService.BookRoomRequest();
            inValue.Body = new Ec1GroupProject.CruiseService.BookRoomRequestBody();
            inValue.Body.rnum = rnum;
            inValue.Body.chin = chin;
            inValue.Body.chout = chout;
            inValue.Body.type = type;
            inValue.Body.nm = nm;
            return ((Ec1GroupProject.CruiseService.CruiseSystemSoap)(this)).BookRoomAsync(inValue);
        }
    }
}
