//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ec1GroupProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public string airline_id { get; set; }
        public string flight_id { get; set; }
        public Nullable<System.DateTime> departdate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Departure { get; set; }
        public string Arrival { get; set; }
        public string Airline { get; set; }
        public string Class { get; set; }
        public string Image { get; set; }
    }
}
