//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ec1GroupProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int roomnum { get; set; }
        public string checkin { get; set; }
        public string checkout { get; set; }
        public string roomtype { get; set; }
        public string name { get; set; }
    }
}
